Question 1:
Write a Python program to convert an array to an ordinary list with the same items.

we can use the np.tolist() function

In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print("Array to list = ", a.tolist())

Array to list =  [[1, 2, 3], [4, 5, 6]]


Question2:
Write a NumPy program to compute the sum of the diagonal elements of a given array.

Hint: Two methods to solve this problem: 1. manually(without direct function). 2. using the trace function

In [11]:
a=np.array([[1,2,3],[4,5,6],[1,2,3]])
print("the given matrix is:                                                                                                          "
      ,
      a)
trace =np.trace(a)
print("sum of the diagonal elements is:", trace)

the given matrix is:                                                                                                           [[1 2 3]
 [4 5 6]
 [1 2 3]]
sum of the diagonal elements is: 9


Question 3

Given an array of your choice, get all the values higher than X :

if a = [[1,2],[3,5]] and x = 3 :  then 3 and 5 are higher than 2. 

In [19]:
a=np.array([[1,2],[3,5]])
x=input("input element x here: ")
x=int(x)
l=[]
b=a.reshape(-1)

for i in b:
    if (i > x):
        l.append(i)
print(l)



input element x here: 2
[3, 5]


Question 4

Given two arrays A&B having the same shape. 

The task is to apply addition by hand: C is the new array. 

In [20]:
a=np.array([[1,2],[3,5]])
b=np.array([[1,2],[3,5]])
c=a+b
print(c)



[[ 2  4]
 [ 6 10]]


Question 5

Write a NumPy program to subtract the mean of each row of a given matrix.

Hint: use the mean function

 

In [34]:
a=np.array([[1,2],[3,5],[1,2],[4,8],[1,12],[9,10]])
m=np.mean(a,axis=1)
print(m)


[1.5 4.  1.5 6.  6.5 9.5]


In [5]:
array=np.eye(7)
print(array)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [6]:
x=np.array([[1,2],[3,4]], dtype=np.float64)
y=np.array([[5,6],[7,8]], dtype=np.float64)
print(x+y)

[[ 6.  8.]
 [10. 12.]]


In [4]:
import pandas as pd
color=["pink", "white", "black", "blue"]
occurence = [20, 15, 6, 43]
S=pd.Series(occurence, index=color)
print(S)

pink     20
white    15
black     6
blue     43
dtype: int64


In [2]:
import pandas as pd
color=["pink", "white", "black", "blue"]
S1=pd.Series([20, 15, 6, 43], index=color)
S2=pd.Series([3, 22, 9, 10], index=color)
print(S1+S2)

pink     23
white    37
black    15
blue     53
dtype: int64
